#!/usr/bin/env python3
"""Build the pandoc source of the APA 7 ``.docx`` from ``manuscript/main.md``, and record what changed.

**There is still no second manuscript.** The ``.docx`` is the second form derived from
``manuscript/main.md``, beside the PDF of ``make_pdf_source.py``, and like it, it is derived by a
small, mechanical, deterministic transformation and read back (``check_docx_text.py``). This
script performs the transformation and writes down every change it makes, in a record of the
conversion (``contract.json``). The check enumerates the same changes from the inputs on its own,
requires the two lists to agree, checks each change against the ``.docx``, and compares the rest
of the text word for word.

What it changes, and why each change is necessary:

1. **The title page replaces the repository's author table.** The level-one heading becomes the
   title; the author and affiliation rows of the table between the ``TMLR:DROP`` markers become the
   byline; and the rows ORCID, Protocol status, Code and data, License and Correspondence become the
   paragraphs of the Author Note, each as ``Label: cell``, verbatim. The bold lead paragraph of that
   block and its closing rule are left out, as the PDF leaves them out. No sentence of the title page
   is written here: every one comes from ``main.md`` or ``CITATION.cff``.
2. **The AI disclosure moves to the Author Note.** The block between the ``TMLR:FOOTNOTE`` markers
   is moved, not copied: the ``.docx`` carries it once, in the Author Note, as the PDF carries it
   once, as a footnote. §K stays an appendix.
3. **The abstract gets its own page**, with the keywords of ``CITATION.cff`` below it, and the title
   is repeated at the top of the first page of text, as APA 7 sets a paper.
4. **Citations become APA author-date citations**, set by pandoc's citeproc with the APA 7 style
   (``manuscript/docx/apa.csl``, vendored). ``[n]`` is a permanent identifier from the central
   bibliography and ``manuscript/refs.json`` holds each entry. Three kinds are handled, and each is
   classified the same way ``make_pdf_source.py`` classifies it (``manuscript/tmlr/citations.tsv``
   is the common record of identifiers and kinds):

   * a parenthetical citation, ``[35, 36, 44]``, becomes one cluster;
   * a narrative citation, where the prose names the authors before the marker (``Hoenig and
     Heisey [44]``), loses the hand-written names, and citeproc sets them with the year
     (``Hoenig and Heisey (2001)``); the names taken out are recorded;
   * a citation inside a parenthesis, ``(§2.3, and [44] on why ...)``, becomes the cluster, with the
     text of the parenthesis as its prefix and suffix, so that the parentheses are not nested.

   Each citation is set in the character style ``Citation``, which changes nothing on the page and
   lets the check find every citation in the ``.docx``. What citeproc set for each is held in
   ``manuscript/docx/citations-apa.tsv``.
5. **The References section becomes the APA reference list**, generated by citeproc from
   ``manuscript/refs.json``, where the rendered block stands. The note after it, on the permanent
   reference numbers, is left out: the ``.docx`` prints no numbers, so it would say nothing.
6. **Figures and tables get APA labels**: a line "Figure N" or "Table N" and a line with the title,
   both above. The figure's title is its caption in ``main.md`` without the label "**Figure N.**";
   the table's is the text of its ``Table:`` line. Tables are numbered in order of appearance. A
   figure is the PNG of the figure ``make_figures.py`` draws from the shipped data, set as a
   standalone PDF and rasterised at 600 dpi.
7. **The references and each appendix begin on a new page**, and the markers in HTML comments and
   the horizontal rules are left out.

Everything else is passed through byte for byte, including the section numbers, which the
repository cites.

The script also writes the two inputs pandoc needs that are not text: the reference document that
carries the APA page and paragraph styles (generated from pandoc's own default, so that a style
change is a diff of this file), and the standalone sources of the figures.

Usage:
    python analysis/scripts/make_docx_source.py --out-dir build/docx --no-preprint
    python analysis/scripts/make_docx_source.py --reference-docx default.docx --out build/docx/reference.docx
    python analysis/scripts/make_docx_source.py --standalone-figures build/docx/figs
    python analysis/scripts/make_docx_source.py --figure-manifest build/docx/figs
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from make_pdf_source import (  # noqa: E402
    _CITE,
    _shielded_spans,
    _textual_forms,
    parse_references,
    weight_table_columns,
)

DROP_BEGIN = "<!-- TMLR:DROP -->"
DROP_END = "<!-- /TMLR:DROP -->"
FOOTNOTE_BEGIN = "<!-- TMLR:FOOTNOTE -->"
FOOTNOTE_END = "<!-- /TMLR:FOOTNOTE -->"
APPENDIX = "<!-- TMLR:APPENDIX -->"
FIGURE_BEGIN = re.compile(r"^<!-- TMLR:FIGURE ([a-z0-9-]+) -->$")
FIGURE_END = "<!-- /TMLR:FIGURE -->"
REFS_BEGIN = "<!-- BEGIN RENDERED FROM manuscript/refs.json -- DO NOT EDIT BY HAND -->"
REFS_END = "<!-- END RENDERED FROM manuscript/refs.json -->"
#: Markers that carry nothing for the ``.docx`` and are left out where they stand.
PLAIN_MARKERS = re.compile(
    r"^<!-- (?:REPORTED-BRANCH: \S+|BEGIN GENERATED FROM \S+ -- DO NOT EDIT BY HAND|"
    r"END GENERATED FROM \S+) -->$"
)
CAPTION_LABEL = re.compile(r"^\*\*Figure (\d+)\.\*\*\s+")

#: The rows of the author table and where each goes. Every row must be one of these: a row this
#: script does not place would otherwise be dropped without a word.
TITLE_ROWS: tuple[str, ...] = ("Author", "Affiliation")
NOTE_ROWS_BEFORE: tuple[str, ...] = ("ORCID", "Protocol status", "Code and data", "License")
NOTE_ROWS_AFTER: tuple[str, ...] = ("Correspondence",)
TABLE_ROWS = frozenset(TITLE_ROWS + NOTE_ROWS_BEFORE + NOTE_ROWS_AFTER)

#: The description an identifier of ``CITATION.cff`` must open with to name the preprint of an
#: earlier version, which the Author Note then declares (design-final §3.5).
PREPRINT_DESCRIPTION = "Preprint of an earlier version"

#: A paragraph that starts a new page and takes no room on it: an empty paragraph in the style
#: ``Page Break`` of the reference document, which breaks the page before itself and is one point
#: high. pandoc passes the raw block through as it is.
PAGE_BREAK = '```{=openxml}\n<w:p><w:pPr><w:pStyle w:val="PageBreak"/></w:pPr></w:p>\n```'

CITATION_STYLE = "Citation"


def _die(message: str) -> None:
    print(f"[docx-source] {message}", file=sys.stderr)
    raise SystemExit(1)


def verify_vendored(repo_root: Path) -> int:
    """Require the vendored citation style to be the bytes ``manuscript/docx/VENDORED.json`` records.

    The reference list is APA 7 only while the style is the APA style as published; a local edit to
    it would still set a reference list that looks like one.
    """
    directory = repo_root / "manuscript" / "docx"
    record = json.loads((directory / "VENDORED.json").read_text(encoding="utf-8"))
    for name, digest in record["sha256"].items():
        actual = hashlib.sha256((directory / name).read_bytes()).hexdigest()
        if actual != digest:
            _die(
                f"manuscript/docx/{name} is not the vendored file VENDORED.json records ({actual[:12]})"
            )
    return len(record["sha256"])


# --------------------------------------------------------------------------------------------------
# CITATION.cff, read without a YAML library (the build runs on the system python3)


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    if len(value) >= 2 and value[0] == value[-1] == "'":
        return value[1:-1].replace("''", "'")
    return value


def read_citation_cff(path: Path) -> dict[str, Any]:
    """The fields of ``CITATION.cff`` the title page needs, read from the file's own layout.

    Only the shapes this file uses are understood -- a quoted or plain scalar, a folded block
    (``>-``), a list of scalars and a list of mappings -- and anything else under a key read here is
    an error rather than a guess. ``check_docx_text.py`` reads the same file with a YAML parser, so
    a misreading here is caught there.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    out: dict[str, Any] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip() or line.lstrip().startswith("#") or line.startswith(" "):
            index += 1
            continue
        match = re.match(r"^([A-Za-z][\w-]*):(?:\s+(.*))?$", line)
        if not match:
            _die(f"CITATION.cff: cannot read the line {line!r}")
        key, value = match.group(1), (match.group(2) or "").strip()
        index += 1
        block: list[str] = []
        while index < len(lines) and (lines[index].startswith(" ") or not lines[index].strip()):
            block.append(lines[index])
            index += 1
        while block and not block[-1].strip():
            block.pop()
        if value == ">-":
            paragraphs: list[list[str]] = [[]]
            for raw in block:
                if raw.strip():
                    paragraphs[-1].append(raw.strip())
                else:
                    paragraphs.append([])
            out[key] = "\n".join(" ".join(p) for p in paragraphs if p)
        elif value:
            if block:
                _die(f"CITATION.cff: {key} has a value and an indented block")
            out[key] = _unquote(value)
        else:
            items: list[Any] = []
            for raw in block:
                if raw.lstrip().startswith("#"):
                    continue
                item = re.match(r"^\s+- (.*)$", raw)
                if item:
                    pair = re.match(r"^([A-Za-z][\w-]*):\s+(.*)$", item.group(1))
                    items.append(
                        {pair.group(1): _unquote(pair.group(2))}
                        if pair
                        else _unquote(item.group(1))
                    )
                    continue
                pair = re.match(r"^\s+([A-Za-z][\w-]*):\s+(.*)$", raw)
                if pair and items and isinstance(items[-1], dict):
                    items[-1][pair.group(1)] = _unquote(pair.group(2))
                    continue
                _die(f"CITATION.cff: cannot read the line {raw!r} under {key}")
            out[key] = items
    return out


def preprint_doi(cff: dict[str, Any], *, no_preprint: bool) -> str | None:
    """The DOI of the preprint the Author Note declares, chosen by the type of its description.

    Exactly one identifier must name it. None is allowed only with ``--no-preprint``, which states
    as a fact of the build that no preprint of this work is public; it is not a way around the check
    (design-final §3.5).
    """
    found = [
        item
        for item in cff.get("identifiers", []) or []
        if isinstance(item, dict)
        and str(item.get("description", "")).startswith(PREPRINT_DESCRIPTION)
    ]
    if any(item.get("type") != "doi" for item in found):
        _die("CITATION.cff: an identifier described as a preprint is not a DOI")
    if len(found) > 1:
        _die(f"CITATION.cff names {len(found)} preprints; the Author Note declares one")
    if not found:
        if no_preprint:
            return None
        _die(
            "CITATION.cff names no preprint. If none is public, build with --no-preprint and record "
            "why; if one is, add it to CITATION.cff"
        )
    if no_preprint:
        _die("--no-preprint was given, but CITATION.cff names a preprint")
    return str(found[0]["value"])


# --------------------------------------------------------------------------------------------------
# The manuscript, cut into blocks with their line numbers


@dataclass
class Block:
    kind: str  # heading, para, item, code, table, figure, marker, rule, footnote, references, note, blank
    start: int  # 0-based index of the first line
    end: int  # one past the last line
    lines: list[str] = field(default_factory=list)
    name: str = ""  # a figure's name, a marker's text
    caption: list[str] = field(default_factory=list)  # a table's caption lines
    caption_start: int = -1


def _is_marker(line: str) -> bool:
    return line.startswith("<!--") and line.rstrip().endswith("-->")


def cut_blocks(lines: list[str], start: int) -> list[Block]:
    """Cut ``lines[start:]`` into blocks. Fails on anything it does not recognise."""
    blocks: list[Block] = []
    i = start
    n = len(lines)
    while i < n:
        line = lines[i]
        stripped = line.strip()
        if not stripped:
            i += 1
            continue
        if _is_marker(stripped):
            figure = FIGURE_BEGIN.match(stripped)
            if stripped == FOOTNOTE_BEGIN:
                j = lines.index(FOOTNOTE_END, i)
                blocks.append(Block("footnote", i, j + 1, lines[i + 1 : j]))
                i = j + 1
            elif figure:
                j = lines.index(FIGURE_END, i)
                blocks.append(Block("figure", i, j + 1, lines[i + 1 : j], name=figure.group(1)))
                i = j + 1
            elif stripped == REFS_BEGIN:
                j = lines.index(REFS_END, i)
                blocks.append(Block("references", i, j + 1, lines[i : j + 1]))
                i = j + 1
                # The note that follows the list, up to the appendix marker.
                while i < n and not lines[i].strip():
                    i += 1
                k = i
                while k < n and lines[k].strip():
                    k += 1
                if i == k:
                    _die("no note follows the rendered reference list")
                blocks.append(Block("note", i, k, lines[i:k]))
                i = k
            else:
                blocks.append(Block("marker", i, i + 1, [line], name=stripped))
                i += 1
            continue
        if stripped == "---":
            blocks.append(Block("rule", i, i + 1, [line]))
            i += 1
            continue
        if stripped.startswith("```"):
            j = i + 1
            while j < n and not lines[j].strip().startswith("```"):
                j += 1
            if j == n:
                _die(f"a fenced code block opened at line {i + 1} is never closed")
            blocks.append(Block("code", i, j + 1, lines[i : j + 1]))
            i = j + 1
            continue
        if line.startswith("#"):
            blocks.append(Block("heading", i, i + 1, [line]))
            i += 1
            continue
        if stripped.startswith("|"):
            j = i
            while j < n and lines[j].strip().startswith("|"):
                j += 1
            block = Block("table", i, j, lines[i:j])
            k = j
            while k < n and not lines[k].strip():
                k += 1
            if k < n and lines[k].startswith("Table: "):
                m = k
                while m < n and lines[m].strip():
                    m += 1
                block.caption = lines[k:m]
                block.caption_start = k
                block.end = m
                j = m
            else:
                _die(f"the table at line {i + 1} has no 'Table:' caption")
            blocks.append(block)
            i = j
            continue
        if re.match(r"^(?:[-+*]|\d+\.) ", line):
            j = i + 1
            while j < n and lines[j].startswith("  ") and lines[j].strip():
                j += 1
            blocks.append(Block("item", i, j, lines[i:j]))
            i = j
            continue
        j = i + 1
        while (
            j < n
            and lines[j].strip()
            and not _is_marker(lines[j].strip())
            and not lines[j].startswith("#")
            and not lines[j].strip().startswith(("|", "```"))
            and not re.match(r"^(?:[-+*]|\d+\.) ", lines[j])
        ):
            j += 1
        blocks.append(Block("para", i, j, lines[i:j]))
        i = j
    return blocks


# --------------------------------------------------------------------------------------------------
# Citations


@dataclass
class Citation:
    k: int
    line: int  # 1-based line of the marker in main.md
    ids: tuple[int, ...]
    kind: str  # parenthetical, narrative, in-parentheses
    removed: str  # the authors' names the prose wrote by hand, for a narrative citation
    prefix: str  # for a citation inside a parenthesis
    suffix: str
    context: str  # the last four words before the marker, as manuscript/tmlr/citations.tsv has it
    mode: str  # citep / citeyearpar, as manuscript/tmlr/citations.tsv has it
    start: int  # offsets into the whole text of what the citation replaces
    end: int


def _paren_depth(text: str) -> int:
    return text.count("(") - text.count(")")


def find_citations(text: str, regions: list[tuple[int, int]], references: Any) -> list[Citation]:
    """Every ``[n]`` marker in ``regions`` of ``text``, outside code, with its kind and extent."""
    by_number = {r.number: r for r in references}
    shielded = _shielded_spans(text)
    out: list[Citation] = []
    for match in _CITE.finditer(text):
        if not any(a <= match.start() < b for a, b in regions):
            continue
        if any(a <= match.start() < b for a, b in shielded):
            continue
        ids = tuple(int(n) for n in match.group(1).split(", "))
        unknown = [n for n in ids if n not in by_number]
        if unknown:
            _die(f"citation [{match.group(1)}] names no entry of the References section: {unknown}")
        before = " ".join(text[max(0, match.start() - 120) : match.start()].split()) + " "
        mode, form = "citep", ""
        if len(ids) == 1:
            for candidate in _textual_forms(by_number[ids[0]]):
                if before.endswith(" " + candidate + " ") or before.endswith("*" + candidate + " "):
                    mode, form = "citeyearpar", candidate
                    break
        context = " ".join(before.split()[-4:])
        line = text.count("\n", 0, match.start()) + 1
        paragraph_start = text.rfind("\n\n", 0, match.start()) + 2
        # Code spans are blanked, not removed, so that an offset into ``lead`` is one into the text.
        lead = re.sub(
            r"`[^`\n]*`", lambda m: "x" * len(m.group(0)), text[paragraph_start : match.start()]
        )
        start, end, prefix, suffix, kind = match.start(), match.end(), "", "", "parenthetical"
        if form:
            words = r"\s+".join(re.escape(w) for w in form.split())
            found = re.search(
                r"(?<=[\s*])" + words + r"\s+$", text[paragraph_start : match.start()]
            )
            if not found:
                _die(f"line {line}: cannot find the names {form!r} before the marker")
            start = paragraph_start + found.start()
            kind = "narrative"
        if _paren_depth(lead) > 0:
            if form:
                _die(f"line {line}: a narrative citation inside a parenthesis is not handled")
            opening = paragraph_start + lead.rfind("(")
            # Only the innermost open parenthesis is read; a nested one is not handled.
            if _paren_depth(lead[lead.rfind("(") + 1 :]) != 0:
                _die(f"line {line}: a citation inside nested parentheses is not handled")
            depth, close = 1, match.end()
            while close < len(text) and depth:
                if text[close] == "(":
                    depth += 1
                elif text[close] == ")":
                    depth -= 1
                close += 1
            if depth:
                _die(f"line {line}: the parenthesis around the citation is never closed")
            prefix = " ".join(text[opening + 1 : match.start()].split())
            suffix = " ".join(text[match.end() : close - 1].split())
            if "@" in prefix + suffix or ";" in prefix + suffix or "[" in prefix + suffix:
                _die(
                    f"line {line}: the text around the citation cannot be a citation's prefix or suffix"
                )
            start, end, kind = opening, close, "in-parentheses"
        out.append(
            Citation(len(out) + 1, line, ids, kind, form, prefix, suffix, context, mode, start, end)
        )
    return out


def citation_markup(cite: Citation) -> str:
    keys = "; ".join(f"@cds{n}" for n in cite.ids)
    if cite.kind == "narrative":
        inner = keys
    elif cite.kind == "in-parentheses":
        inner = f"[{cite.prefix} {keys} {cite.suffix}]"
    else:
        inner = f"[{keys}]"
    return f'[{inner}]{{custom-style="{CITATION_STYLE}"}}'


def check_against_tmlr_fixture(repo_root: Path, cites: list[Citation]) -> None:
    """The kinds and identifiers must be those ``make_pdf_source.py`` records, row for row."""
    path = repo_root / "manuscript" / "tmlr" / "citations.tsv"
    rows = [r.split("\t") for r in path.read_text(encoding="utf-8").splitlines()[1:]]
    mine = [[c.context, ", ".join(map(str, c.ids)), c.mode] for c in cites]
    if rows != mine:
        for k, (want, have) in enumerate(zip(rows, mine, strict=False), start=1):
            if want != have:
                _die(f"citation {k}: {path.name} has {want}, this build reads {have}")
        _die(f"{path.name} has {len(rows)} citations, this build reads {len(mine)}")


# --------------------------------------------------------------------------------------------------
# The source


def _div(style: str, text: str) -> str:
    return f'::: {{custom-style="{style}"}}\n{text}\n:::'


def _table_rows(lines: list[str]) -> list[list[str]]:
    rows = []
    for line in lines:
        cells = re.split(r"(?<!\\)\|", line.strip())[1:-1]
        rows.append([c.strip() for c in cells])
    return rows


def parse_author_table(
    inner: list[str], offset: int
) -> tuple[dict[str, tuple[int, str]], list[int]]:
    """The rows of the author table, label -> (1-based line, cell), and the lines left out."""
    rows: dict[str, tuple[int, str]] = {}
    dropped: list[int] = []
    for index, line in enumerate(inner):
        number = offset + index + 1
        if not line.strip():
            continue
        if line.startswith("| ") and not re.fullmatch(r"\|\s*\|\s*\|", line.strip()):
            cells = _table_rows([line])[0]
            if len(cells) != 2:
                _die(f"line {number}: an author-table row must have two cells")
            label, cell = cells
            if label not in TABLE_ROWS:
                _die(
                    f"line {number}: the author table has a row {label!r} this build does not place"
                )
            rows[label] = (number, cell)
        else:
            dropped.append(number)
    missing = TABLE_ROWS - set(rows)
    if missing:
        _die(f"the author table has no row {sorted(missing)}")
    return rows, dropped


def build(repo_root: Path, *, no_preprint: bool) -> tuple[str, dict[str, Any]]:
    manuscript = repo_root / "manuscript" / "main.md"
    text = manuscript.read_text(encoding="utf-8")
    lines = text.split("\n")
    cff = read_citation_cff(repo_root / "CITATION.cff")
    doi = preprint_doi(cff, no_preprint=no_preprint)
    references = parse_references(text)

    if not lines[0].startswith("# "):
        _die("the first line of main.md is not the level-one heading")
    title = lines[0][2:].strip()
    if title != cff.get("title"):
        _die("the title of main.md is not the title of CITATION.cff")

    drop_begin, drop_end = lines.index(DROP_BEGIN), lines.index(DROP_END)
    if any(line.strip() for line in lines[1:drop_begin]):
        _die("the TMLR:DROP block must follow the title directly")
    rows, dropped_lines = parse_author_table(lines[drop_begin + 1 : drop_end], drop_begin + 1)

    abstract_head = lines.index("## Abstract", drop_end)
    abstract_end = lines.index("---", abstract_head)
    abstract = " ".join(" ".join(lines[abstract_head + 1 : abstract_end]).split())
    if abstract != " ".join(str(cff.get("abstract", "")).split()):
        _die("the abstract of main.md is not the abstract of CITATION.cff")

    blocks = cut_blocks(lines, abstract_end + 1)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line) + 1)
    regions = [
        (offsets[b.start], offsets[b.end])
        for b in blocks
        if b.kind in ("para", "item", "heading", "table", "figure")
    ]
    cites = find_citations(text, regions, references)
    for block in blocks:
        if block.kind in ("table", "figure") and any(
            offsets[block.start] <= c.start < offsets[block.end] for c in cites
        ):
            # Their labels and titles are set above them, so a citation in them would be out of the
            # order citeproc and the check number citations in.
            _die(
                f"line {block.start + 1}: a citation in a table or a figure caption is not handled"
            )
    check_against_tmlr_fixture(repo_root, cites)
    cited = {n for c in cites for n in c.ids}
    uncited = sorted({r.number for r in references} - cited)
    if uncited:
        _die(f"the References section lists entries nothing cites: {uncited}")

    def with_citations(block: Block) -> str:
        """The block's text with each citation in it replaced by its pandoc markup."""
        a, b = offsets[block.start], offsets[block.end] - 1
        own = [c for c in cites if a <= c.start < b]
        if any(c.end > b for c in own):
            _die(f"a citation runs past the block at line {block.start + 1}")
        out, cursor = [], a
        for cite in own:
            out.append(text[cursor : cite.start])
            out.append(citation_markup(cite))
            cursor = cite.end
        out.append(text[cursor:b])
        return "".join(out)

    record: dict[str, Any] = {
        "source": "manuscript/main.md",
        "source_sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
        "citations": [
            {
                "k": c.k,
                "line": c.line,
                "ids": list(c.ids),
                "kind": c.kind,
                "removed": c.removed,
                "prefix": c.prefix,
                "suffix": c.suffix,
            }
            for c in cites
        ],
        "head": {
            "title": title,
            "author": rows["Author"][1],
            "affiliation": rows["Affiliation"][1],
            "abstract_lines": [abstract_head + 2, abstract_end],
            "keywords": list(cff.get("keywords", [])),
            "preprint_doi": doi,
        },
        "author_note": [],
        "figures": [],
        "tables": [],
        "drops": [],
        "bibliography": {
            "lines": [],
            "ids": [r.number for r in references],
        },
        "page_breaks": [],
    }
    record["drops"].append({"what": "author table, left out", "lines": dropped_lines})

    out: list[str] = []
    out.append(_div("Title", title))
    out.append(_div("Author", rows["Author"][1]))
    out.append(_div("Affiliation", rows["Affiliation"][1]))
    out.append(_div("Author Note Heading", "Author Note"))
    for label in NOTE_ROWS_BEFORE:
        number, cell = rows[label]
        out.append(_div("Author Note", f"{label}: {cell}"))
        record["author_note"].append({"what": label, "lines": [number, number]})
    if doi is not None:
        # The one sentence of the title page this script writes: the identifier is a fact of the
        # archive, and the sentence states only that the preprint is of an earlier version.
        out.append(
            _div(
                "Author Note",
                f"Preprint: an earlier version is available at https://doi.org/{doi}.",
            )
        )
        record["author_note"].append({"what": "Preprint", "lines": []})

    ai = [b for b in blocks if b.kind == "footnote"]
    if len(ai) != 1:
        _die("main.md must carry exactly one TMLR:FOOTNOTE block")
    ai_text = "\n".join(ai[0].lines).strip()
    if not ai_text:
        _die("the TMLR:FOOTNOTE block is empty")
    out.append(_div("Author Note", ai_text))
    record["author_note"].append(
        {"what": "AI disclosure", "lines": [ai[0].start + 2, ai[0].end - 1]}
    )
    for label in NOTE_ROWS_AFTER:
        number, cell = rows[label]
        out.append(_div("Author Note", f"{label}: {cell}"))
        record["author_note"].append({"what": label, "lines": [number, number]})

    out.append(_div("Abstract Title", "Abstract"))
    out.append(_div("Abstract", "\n".join(lines[abstract_head + 1 : abstract_end]).strip()))
    keywords = cff.get("keywords") or []
    if not keywords:
        _die("CITATION.cff carries no keywords")
    out.append(_div("Keywords", "*Keywords:* " + ", ".join(keywords)))
    out.append(_div("Title Repeat", title))

    table_number = 0
    figure_number = 0
    appendix = False
    previous: Block | None = None
    for block in blocks:
        span = [block.start + 1, block.end]
        # An item that follows another with no blank line between them in main.md continues the same
        # tight list, so it is joined to it with a single line break rather than a blank line.
        joined = (
            block.kind == "item"
            and previous is not None
            and previous.kind == "item"
            and previous.end == block.start
        )
        previous = block
        if joined:
            out[-1] += "\n" + with_citations(block)
            continue
        if block.kind == "footnote":
            record["drops"].append(
                {"what": "AI disclosure, moved to the Author Note", "lines": span}
            )
        elif block.kind == "marker":
            if block.name == APPENDIX:
                appendix = True
            elif not PLAIN_MARKERS.match(block.name):
                _die(f"line {block.start + 1}: a marker this build does not know: {block.name}")
            record["drops"].append({"what": "marker", "lines": span, "text": block.name})
        elif block.kind == "rule":
            record["drops"].append({"what": "rule", "lines": span})
        elif block.kind == "references":
            record["bibliography"]["lines"] = span
            out.append("::: {#refs}\n:::")
        elif block.kind == "note":
            record["drops"].append(
                {
                    "what": "note after the references",
                    "lines": span,
                    "text": " ".join(" ".join(block.lines).split()),
                }
            )
        elif block.kind == "heading":
            heading = block.lines[0]
            if heading == "## References" or (appendix and re.match(r"^## [A-Z]\. ", heading)):
                out.append(PAGE_BREAK)
                record["page_breaks"].append(block.start + 1)
            out.append(heading)
        elif block.kind == "figure":
            figure_number += 1
            caption = "\n".join(block.lines).strip()
            label = CAPTION_LABEL.match(caption)
            if not label or int(label.group(1)) != figure_number:
                _die(
                    f"figure {block.name} is not labelled Figure {figure_number} in order of appearance"
                )
            body = with_citations(block)
            body = body[body.index("**Figure") :].replace(FIGURE_END, "").strip()
            body = CAPTION_LABEL.sub("", body, count=1)
            out.append(_div("Figure Number", f"Figure {figure_number}"))
            out.append(_div("Figure Title", body))
            out.append(_div("Figure Image", f"![](figs/fig-{block.name}.png)"))
            record["figures"].append({"number": figure_number, "name": block.name, "lines": span})
        elif block.kind == "table":
            table_number += 1
            source = with_citations(block)
            table_lines = source.split("\n")[: len(block.lines)]
            caption = "\n".join(source.split("\n")[block.caption_start - block.start :]).strip()
            caption = caption.removeprefix("Table: ").strip()
            weighted, _ = weight_table_columns("\n".join(table_lines))
            out.append(_div("Table Number", f"Table {table_number}"))
            out.append(_div("Table Title", caption))
            out.append(weighted)
            record["tables"].append(
                {
                    "number": table_number,
                    "lines": [block.start + 1, block.start + len(block.lines)],
                    "caption_line": block.caption_start + 1,
                }
            )
        elif block.kind in ("para", "item"):
            out.append(with_citations(block))
        elif block.kind == "code":
            out.append("\n".join(block.lines))
        else:
            _die(f"line {block.start + 1}: unhandled block {block.kind}")
    if not record["bibliography"]["lines"]:
        _die("main.md has no rendered reference list")
    if figure_number == 0 or table_number == 0:
        _die("the manuscript carries no figure or no table")

    return "\n\n".join(out) + "\n", record


# --------------------------------------------------------------------------------------------------
# The reference document

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"

#: Times New Roman 12, double-spaced, no space between paragraphs (APA 7, 2.19 to 2.24). Set as
#: defaults rather than on Normal, so that a table style can set its own size and spacing.
DOC_DEFAULTS = (
    "<w:docDefaults><w:rPrDefault><w:rPr>"
    '<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman" '
    'w:cs="Times New Roman"/><w:sz w:val="24"/><w:szCs w:val="24"/>'
    '<w:lang w:val="en-US" w:eastAsia="en-US" w:bidi="ar-SA"/></w:rPr></w:rPrDefault>'
    '<w:pPrDefault><w:pPr><w:spacing w:before="0" w:after="0" w:line="480" w:lineRule="auto"/>'
    "</w:pPr></w:pPrDefault></w:docDefaults>"
)


def _pstyle(
    style_id: str,
    name: str,
    ppr: str = "",
    rpr: str = "",
    based: str = "Normal",
    custom: bool = True,
    extra: str = "",
) -> str:
    flag = ' w:customStyle="1"' if custom else ""
    return (
        f'<w:style w:type="paragraph"{flag} w:styleId="{style_id}"><w:name w:val="{name}"/>'
        f'<w:basedOn w:val="{based}"/>{extra}<w:qFormat/>'
        f"<w:pPr>{ppr}</w:pPr><w:rPr>{rpr}</w:rPr></w:style>"
    )


def _cstyle(style_id: str, name: str, rpr: str) -> str:
    return (
        f'<w:style w:type="character" w:customStyle="1" w:styleId="{style_id}"><w:name w:val="{name}"/>'
        f'<w:basedOn w:val="DefaultParagraphFont"/><w:rPr>{rpr}</w:rPr></w:style>'
    )


INDENT = '<w:ind w:firstLine="720"/>'
NO_INDENT = '<w:ind w:firstLine="0"/>'
CENTER = '<w:jc w:val="center"/>'
BOLD = "<w:b/><w:bCs/>"
ITALIC = "<w:i/><w:iCs/>"
KEEP = "<w:keepNext/>"
SINGLE = '<w:spacing w:line="240" w:lineRule="auto"/>'

#: The styles the reference document defines, replacing pandoc's defaults of the same identifier.
STYLES: tuple[str, ...] = (
    _pstyle("Normal", "Normal", custom=False, based="").replace('<w:basedOn w:val=""/>', ""),
    _pstyle("BodyText", "Body Text", INDENT, custom=False, extra='<w:link w:val="BodyTextChar"/>'),
    _pstyle(
        "FirstParagraph", "First Paragraph", based="BodyText", extra='<w:next w:val="BodyText"/>'
    ),
    _pstyle("Compact", "Compact", NO_INDENT, based="BodyText"),
    _pstyle(
        "Title",
        "Title",
        CENTER + KEEP + '<w:spacing w:before="2880" w:after="480"/>',
        BOLD,
        custom=False,
    ),
    _pstyle("Author", "Author", CENTER + KEEP),
    _pstyle("Affiliation", "Affiliation", CENTER + KEEP),
    _pstyle(
        "AuthorNoteHeading",
        "Author Note Heading",
        CENTER + KEEP + '<w:spacing w:before="2400"/>',
        BOLD,
    ),
    _pstyle("AuthorNote", "Author Note", INDENT),
    _pstyle("AbstractTitle", "Abstract Title", "<w:pageBreakBefore/>" + CENTER + KEEP, BOLD),
    _pstyle("Abstract", "Abstract", NO_INDENT),
    _pstyle("Keywords", "Keywords", INDENT),
    _pstyle("TitleRepeat", "Title Repeat", "<w:pageBreakBefore/>" + CENTER + KEEP, BOLD),
    _pstyle(
        "Heading1",
        "heading 1",
        CENTER + KEEP + '<w:outlineLvl w:val="0"/>',
        BOLD,
        custom=False,
        extra='<w:next w:val="BodyText"/>',
    ),
    _pstyle(
        "Heading2",
        "heading 2",
        KEEP + '<w:outlineLvl w:val="1"/>',
        BOLD,
        custom=False,
        extra='<w:next w:val="BodyText"/>',
    ),
    _pstyle(
        "Heading3",
        "heading 3",
        KEEP + '<w:outlineLvl w:val="2"/>',
        BOLD + ITALIC,
        custom=False,
        extra='<w:next w:val="BodyText"/>',
    ),
    _pstyle("Bibliography", "Bibliography", '<w:ind w:left="720" w:hanging="720"/>', custom=False),
    _pstyle("FigureNumber", "Figure Number", KEEP + '<w:spacing w:before="240"/>', BOLD),
    _pstyle("FigureTitle", "Figure Title", KEEP, ITALIC),
    _pstyle("FigureImage", "Figure Image", CENTER),
    _pstyle("TableNumber", "Table Number", KEEP + '<w:spacing w:before="240"/>', BOLD),
    _pstyle("TableTitle", "Table Title", KEEP, ITALIC),
    _pstyle(
        "SourceCode",
        "Source Code",
        SINGLE + '<w:spacing w:before="120" w:after="120" w:line="240" w:lineRule="auto"/>',
        '<w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="20"/><w:szCs w:val="20"/>',
    ),
    _pstyle(
        "PageBreak",
        "Page Break",
        '<w:pageBreakBefore/><w:spacing w:line="20" w:lineRule="exact"/>',
        '<w:sz w:val="2"/><w:szCs w:val="2"/>',
    ),
    _cstyle(
        "VerbatimChar",
        "Verbatim Char",
        '<w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:sz w:val="22"/><w:szCs w:val="22"/>',
    ),
    _cstyle("Citation", CITATION_STYLE, ""),
    # APA tables: rules above and below the table and under the heading row, none between cells;
    # set single-spaced in 10 point (APA 7, 7.21). Set on the table style, which paragraph styles that
    # set neither size nor line spacing leave in force.
    '<w:style w:type="table" w:default="1" w:styleId="Table"><w:name w:val="Table"/>'
    '<w:basedOn w:val="TableNormal"/><w:qFormat/>'
    '<w:pPr><w:spacing w:line="240" w:lineRule="auto"/></w:pPr><w:rPr><w:sz w:val="20"/><w:szCs w:val="20"/></w:rPr>'
    '<w:tblPr><w:tblInd w:w="0" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="8" w:space="0" w:color="000000"/>'
    '<w:bottom w:val="single" w:sz="8" w:space="0" w:color="000000"/></w:tblBorders>'
    '<w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="108" w:type="dxa"/>'
    '<w:bottom w:w="0" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr>'
    '<w:tblStylePr w:type="firstRow"><w:rPr>' + BOLD + "</w:rPr><w:tcPr><w:tcBorders>"
    '<w:bottom w:val="single" w:sz="8" w:space="0" w:color="000000"/></w:tcBorders>'
    '<w:vAlign w:val="bottom"/></w:tcPr></w:tblStylePr></w:style>',
)

#: Letter, one-inch margins, and the page number at the top right of every page (APA 7, 2.18, 2.22).
SECTION = (
    '<w:sectPr><w:headerReference w:type="default" r:id="rIdApaHeader"/>'
    '<w:pgSz w:w="12240" w:h="15840"/>'
    '<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" '
    'w:footer="720" w:gutter="0"/></w:sectPr>'
)
HEADER = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    f'<w:hdr xmlns:w="{W}" xmlns:r="{R}"><w:p><w:pPr><w:jc w:val="right"/>'
    '<w:spacing w:line="240" w:lineRule="auto"/></w:pPr>'
    '<w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText xml:space="preserve"> PAGE </w:instrText></w:r>'
    '<w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>1</w:t></w:r>'
    '<w:r><w:fldChar w:fldCharType="end"/></w:r></w:p></w:hdr>'
)
FIXED_TIME = (1980, 1, 1, 0, 0, 0)


def _replace_styles(styles: str) -> str:
    styles, count = re.subn(r"<w:docDefaults>.*?</w:docDefaults>", DOC_DEFAULTS, styles, flags=re.S)
    if count != 1:
        _die("the default reference document has no single w:docDefaults")
    for definition in STYLES:
        style_id = re.search(r'w:styleId="([^"]+)"', definition).group(1)
        styles = re.sub(
            r'<w:style\b[^>]*\bw:styleId="' + re.escape(style_id) + r'"[^>]*>.*?</w:style>\s*',
            "",
            styles,
            flags=re.S,
        )
    if styles.count("</w:styles>") != 1:
        _die("the default reference document's styles part does not close once")
    return styles.replace("</w:styles>", "".join(STYLES) + "</w:styles>")


def make_reference_docx(default: bytes) -> bytes:
    """The reference document: pandoc's default, with the APA page and styles, written reproducibly.

    Every entry is written with the same fixed time, in the order the default holds them, so that
    two runs from the same pandoc produce the same bytes whatever the time and the directory.
    """
    source = zipfile.ZipFile(io.BytesIO(default))
    names = source.namelist()
    parts = {name: source.read(name) for name in names}
    styles = _replace_styles(parts["word/styles.xml"].decode("utf-8"))
    parts["word/styles.xml"] = styles.encode("utf-8")
    document = parts["word/document.xml"].decode("utf-8")
    document, count = re.subn(
        r"<w:sectPr\s*/>|<w:sectPr>.*?</w:sectPr>", SECTION, document, flags=re.S
    )
    if count != 1:
        _die("the default reference document has no single w:sectPr")
    if 'xmlns:r="' not in document[: document.index(">", document.index("<w:document"))]:
        _die("the default reference document does not declare the relationships namespace")
    parts["word/document.xml"] = document.encode("utf-8")
    rels = parts["word/_rels/document.xml.rels"].decode("utf-8")
    rels = rels.replace(
        "</Relationships>",
        '<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" '
        'Id="rIdApaHeader" Target="header1.xml" /></Relationships>',
    )
    parts["word/_rels/document.xml.rels"] = rels.encode("utf-8")
    types = parts["[Content_Types].xml"].decode("utf-8")
    types = types.replace(
        "</Types>",
        '<Override PartName="/word/header1.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml" /></Types>',
    )
    parts["[Content_Types].xml"] = types.encode("utf-8")
    core = parts["docProps/core.xml"].decode("utf-8")
    core = re.sub(r"<dcterms:(created|modified)\b[^>]*>[^<]*</dcterms:\1>", "", core)
    parts["docProps/core.xml"] = core.encode("utf-8")
    parts["word/header1.xml"] = HEADER.encode("utf-8")
    order = [*names]
    order.insert(order.index("word/document.xml") + 1, "word/header1.xml")
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as out:
        for name in order:
            info = zipfile.ZipInfo(name, date_time=FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = 3
            info.external_attr = 0o644 << 16
            out.writestr(info, parts[name])
    return buffer.getvalue()


# --------------------------------------------------------------------------------------------------
# Figures

#: The figure as the PDF sets it: ``make_figures.py``'s TikZ in the TMLR text width and fonts, at
#: ``\small``, with the glyph-to-Unicode map so that its numbers read back as text.
STANDALONE = r"""\documentclass[border=4pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath,amssymb}
\usepackage{tikz}
\usetikzlibrary{patterns,positioning}
\input{glyphtounicode}
\pdfgentounicode=1
\setlength{\textwidth}{6.5in}
\begin{document}
{\small\input{fig-NAME}}
\end{document}
"""


def figure_names(repo_root: Path) -> list[str]:
    text = (repo_root / "manuscript" / "main.md").read_text(encoding="utf-8")
    return [m.group(1) for m in re.finditer(r"^<!-- TMLR:FIGURE ([a-z0-9-]+) -->$", text, re.M)]


def write_standalone(repo_root: Path, directory: Path) -> list[str]:
    names = figure_names(repo_root)
    for name in names:
        if not (directory / f"fig-{name}.tex").is_file():
            _die(
                f"{directory}/fig-{name}.tex is missing; run make_figures.py --out-dir {directory}"
            )
        (directory / f"fig-{name}-standalone.tex").write_text(
            STANDALONE.replace("NAME", name), encoding="utf-8", newline="\n"
        )
    return names


def write_manifest(repo_root: Path, directory: Path) -> dict[str, Any]:
    figures = []
    for number, name in enumerate(figure_names(repo_root), start=1):
        png = directory / f"fig-{name}.png"
        if not png.is_file():
            _die(f"{png} is missing")
        figures.append(
            {
                "number": number,
                "name": name,
                "png": png.name,
                "sha256": hashlib.sha256(png.read_bytes()).hexdigest(),
            }
        )
    if len({f["sha256"] for f in figures}) != len(figures):
        _die("two figures have the same PNG")
    manifest = {"figures": figures}
    (directory / "figures.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    return manifest


# --------------------------------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--out-dir", type=Path, help="write paper-source.md and contract.json here")
    mode.add_argument("--reference-docx", type=Path, help="pandoc's default reference.docx")
    mode.add_argument(
        "--standalone-figures", type=Path, help="the directory make_figures.py wrote to"
    )
    mode.add_argument(
        "--figure-manifest", type=Path, help="the directory holding the figures' PNGs"
    )
    parser.add_argument("--out", type=Path, help="with --reference-docx: where to write it")
    parser.add_argument(
        "--no-preprint",
        action="store_true",
        help="no preprint of this work is public, so the Author Note declares none (record why)",
    )
    args = parser.parse_args(argv)

    if args.reference_docx:
        if not args.out:
            parser.error("--reference-docx needs --out")
        data = make_reference_docx(args.reference_docx.read_bytes())
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_bytes(data)
        print(
            f"[docx-source] wrote {args.out} ({len(data)} bytes, sha256 {hashlib.sha256(data).hexdigest()[:16]})"
        )
        return 0
    if args.standalone_figures:
        names = write_standalone(args.repo_root, args.standalone_figures)
        print(f"[docx-source] wrote the standalone sources of {', '.join(names)}")
        return 0
    if args.figure_manifest:
        manifest = write_manifest(args.repo_root, args.figure_manifest)
        print(f"[docx-source] recorded {len(manifest['figures'])} figure PNGs in figures.json")
        return 0

    vendored = verify_vendored(args.repo_root)
    print(f"[docx-source] the {vendored} vendored citation style file matches VENDORED.json")
    source, record = build(args.repo_root, no_preprint=args.no_preprint)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "paper-source.md").write_text(source, encoding="utf-8", newline="\n")
    (args.out_dir / "contract.json").write_text(
        json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )
    kinds = {
        k: sum(1 for c in record["citations"] if c["kind"] == k)
        for k in ("parenthetical", "narrative", "in-parentheses")
    }
    print(
        f"[docx-source] {len(record['citations'])} citations {kinds}, {len(record['figures'])} figures, "
        f"{len(record['tables'])} tables, {len(record['author_note'])} Author Note paragraphs, "
        f"{len(record['drops'])} items left out, {len(record['page_breaks'])} page breaks; "
        f"preprint {'declared' if record['head']['preprint_doi'] else 'none (--no-preprint)'}"
    )
    print(f"[docx-source] wrote {args.out_dir}/paper-source.md and contract.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
